project_name: wego
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  prerelease: auto
archives:
  -
   format: binary
   replacements:
     amd64: x86_64
   name_template: "wego-{{.Os}}-{{.Arch}}"
builds:
  - <<: &build_defaults
      binary: "wego-{{.Os}}-{{.Arch}}"
      main: ./cmd/wego
      ldflags:
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.Version={{.Version}}
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.BuildTime={{.Date}}
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.Branch={{ .Env.BRANCH}}
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.GitCommit={{.Commit}}
        - -X github.com/weaveworks/weave-gitops/pkg/version.FluxVersion={{ .Env.FLUX_VERSION }}
      env:
        - CGO_ENABLED=0
      hooks:
        pre:
          - curl -L https://github.com/fluxcd/flux2/releases/download/v{{.Env.FLUX_VERSION}}/flux_{{.Env.FLUX_VERSION}}_{{.Os}}_{{.Arch}}.tar.gz -o flux-tar.gz
          - tar -xvzf flux-tar.gz
          - mkdir -p ./pkg/flux/bin
          - mv ./flux ./pkg/flux/bin/flux
          - rm flux-tar.gz
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - 7
  - <<: *build_defaults
    id: linux-arm
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
  - <<: *build_defaults
    id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64

