project_name: wego
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - <<: &build_defaults
      binary: wego
      main: ./cmd/wego
      ldflags:
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.BuildTime={{.Date}}
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.Branch={{ .Env.BRANCH}}
        - -X github.com/weaveworks/weave-gitops/cmd/wego/version.GitCommit={{.Commit}}
        - -X github.com/weaveworks/weave-gitops/pkg/version.FluxVersion={{ .Env.FLUX_VERSION }}
      env:
        - CGO_ENABLED=0
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64