apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: "ghcr.io/weaveworks/wego-app:{{.Chart.AppVersion}}"
          args: ["ui", "run", "-l", "--helm-repo-namespace","{{.Values.namespace}}"]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: wego-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-resources
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: weave-gitops-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "*" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "*" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "helmrepositories" ]
    verbs: [ "*" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "gitrepositories" ]
    verbs: [ "*" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-app-service-account
  namespace: {{.Values.namespace}}
secrets:
  - name: wego-app-service-account-token
---
apiVersion: v1
kind: Service
metadata:
  name: wego-app
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: wego-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001