apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wego.app.crd
spec:
  group: app.crd
  scope: Namespaced
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["url"]
          properties:
            url:
              type: "string"
              minimum: 1
              maximum: 1
  versions:
    - name: v1alpha1
      served: true
      storage: true
