---
image:
  tag: latest
  pullPolicy: Always
  repository: localhost:5001/weaveworks/wego-app

logLevel: debug

adminUser:
  create: true
  username: dev
  # 'dev'
  passwordHash: $2y$10$pcy9FV0WMQZUHFDcud8JuecIxlUS/Eh9X.iitZtJEYYHUhKyzlJYm

additionalArgs:
  - "--dev-mode"
