---
apiVersion: v1
kind: Namespace
metadata:
  name: wego-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: wego-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: localhost:5000/weaveworks/wego-app:latest
          args: ["ui", "run", "-l", "--helm-repo-namespace", "wego-system"]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: wego-app
