name: Helm chart

on:
  push:
    branches:
      - 'main'
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/**'

jobs:
  helm-verify:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find new version
        id: new_version
        run: |
          NEW_VERSION=$(yq e '.version' charts/gitops-server/Chart.yaml)
          echo "::set-output name=version::$NEW_VERSION"
      - name: Find old version
        id: old_version
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}
          OLD_VERSION=$(yq e '.version' charts/gitops-server/Chart.yaml)
          echo "::set-output name=version::$OLD_VERSION"
      - name: Alert about the need to change chart version
        run: |
          echo "This PR changed the helm chart. You need to change chart version when you change the chart"
          exit 1
        if: ${{ steps.new_version.outputs.version == steps.old_version.outputs.version }}


  helm-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - name: Generate new chart
        run: |
          URL=https://helm.gitops.weave.works
          mkdir helm-release
          helm package charts/gitops-server/ -d helm-release
          curl -O $URL/index.yaml
          helm repo index helm-release --merge=index.yaml --url=$URL
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.PROD_DOCS_GITOPS_UPLOAD }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: helm-release
          destination: helm.gitops.weave.works
          parent: false
