on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy
jobs:
  publish-s3-artifact:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Setup Kubernetes
      uses: helm/kind-action@v1.1.0
      with:
        cluster_name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.10.0"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WKP_EXAMPLE_ORG_SSH_KEY }}
    - name: build
      run: make all BINARY_NAME=wego-${{matrix.os}}
    - name: User Acceptance Tests (Ubuntu)
      env:
        GITHUB_ORG: wkp-example-org
        GITHUB_TOKEN: "${{ secrets.WKP_EXAMPLE_ORG_KEY }}"

        GITHUB_KEY: "${{ secrets.WKP_EXAMPLE_ORG_SSH_KEY }}"
        WEGO_BIN_PATH: "$(pwd)/bin/wego"
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "test-user@weave.works"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
        export WEGO_BIN_PATH=$(pwd)/bin/wego-${{matrix.os}}
        go test -v -tags=acceptance ./test/acceptance/test/...
      if: matrix.os == 'ubuntu-latest'
    - name: Smoke Tests (macOS)
      run: |
        export WEGO_BIN_PATH=$(pwd)/bin/wego-${{matrix.os}}
        go test -v -tags=smoke ./test/acceptance/test/...
      if: matrix.os == 'macos-latest'

    - name: publish
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws s3 cp bin/wego-${{matrix.os}} s3://weave-gitops/wego-${{matrix.os}}
