on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy
jobs:
  publish-s3-artifact:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: make all BINARY_NAME=wego-${{matrix.os}}
    - name: publish
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws s3 cp bin/wego-${{matrix.os}} s3://weave-gitops/wego-${{matrix.os}}
