on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    outputs:
        gitsha: ${{steps.gitsha.outputs.sha}}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clean
      run: make clean
    - id: gitsha
      run: |
        gitsha=$(git rev-parse --short "$GITHUB_SHA")
        echo "::set-output name=sha::$gitsha"
    - name: build
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        make all BINARY_NAME=gitops-${{matrix.os}}-${{steps.gitsha.outputs.sha}}
    - name: Store gitops binaries
      uses: actions/upload-artifact@v2
      with:
          name: gitops-binaries
          path: bin
          retention-days: 1

  coverage:
    env:
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
        CHECKPOINT_DISABLE: 1
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: checkout
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    - name: Build UI Assets
      run: make cmd/gitops/ui/run/dist/main.js
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Set up flux dir but let dependencies install flux
      run: mkdir -p pkg/flux/bin && tools/download-deps.sh $PWD/tools/dependencies.toml
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.11.0"
        image: kindest/node:v1.20.7
        config: "./test/acceptance/test/configs/kind-config.yaml"
    - name: Fake Install flux
      run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
    - name: unit tests with coverage
      run: |
        go get -u github.com/jstemmer/go-junit-report
        mkdir artefacts
        go test -cover  -covermode=atomic -coverprofile=artefacts/.coverprofile-unittests -v ./... -tags unittest | go-junit-report > artefacts/unit-test-results.xml
    - name: Store unit test coverage results
      uses: actions/upload-artifact@v2
      with:
          name: unit-tests-artefacts
          path: artefacts
          retention-days: 1

  publish-binaries:
    runs-on: ${{matrix.os}}
    needs: [build, acceptance-tests]
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Download gitops binaries
      uses: actions/download-artifact@v2
      with:
        name: gitops-binaries
        path: bin
    - name: publish to s3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws s3 cp bin/gitops-${{matrix.os}}-${{needs.build.outputs.gitsha}} s3://weave-gitops/
        aws s3 cp s3://weave-gitops/gitops-${{matrix.os}}-${{needs.build.outputs.gitsha}} s3://weave-gitops/gitops-${{matrix.os}}

