name: Helm Chart Test

on:
  pull_request: {}

jobs:
  test:
    name: Helm Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run check
        run: |
          helm lint helm/weave-gitops
          kind create cluster
          helm install --dry-run --debug weave-gitops helm/weave-gitops
          kind delete cluster