on:
  schedule:
    - cron: '0 0 * * Mon-Sat'
    - cron: '0 0 * * Sun'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: weaveworks/wego-app
  USE_NIGHTLY_BUILD_TAG: "true"

name: Nightly
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clean
      run: make clean
    - name: build
      run: make all BINARY_NAME=gitops-${{matrix.os}}-nightly
    - name: Store gitops binaries
      uses: actions/upload-artifact@v2
      with:
          name: gitops-binaries-${{matrix.os}}-nightly
          path: bin
          retention-days: 1

  publish:
    if: success()
    needs: [test-eks, test-gke]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Download tested gitops binaries
      uses: actions/download-artifact@v2
      with:
        name: gitops-binaries-${{matrix.os}}-nightly
        path: bin
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: publish nightly binaries to s3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: |
        aws s3 cp bin/gitops-${{matrix.os}}-nightly s3://weave-gitops/nightly/${{ steps.date.outputs.date }}/gitops-${{matrix.os}}
