name: Code Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  fossa:
    name: FOSSA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.X
      - name: Fake Install flux
        run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
      - name: Fake dist for the ui cmd
        run: mkdir -p cmd/gitops/ui/run/dist && touch cmd/gitops/ui/run/dist/index.js
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
          github-token: ${{ github.token }}

  snyk-sourcecode:
    name: Snyk Sourcecode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fake Install flux
        run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
      - name: Remove UI deps from Scan
        run: rm package-lock.json && rm package.json && make cmd/gitops/ui/run/dist/index.html
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          args: --sarif-file-output=snyk.code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.code.sarif
      - name: Remove fake flux
        run: rm -rv pkg/flux/bin

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
