
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fake Install flux
      run: mkdir -p cmd/wego/flux/bin && touch cmd/wego/flux/bin/flux
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
    - name: Remove fake flux
      run: rm -rv cmd/wego/flux/bin

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fake Install flux
      run: mkdir -p cmd/wego/flux/bin && touch cmd/wego/flux/bin/flux
    - name: Run tests
      run: make unit-tests
    - name: Remove fake flux
      run: rm -rv cmd/wego/flux/bin

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov