
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install UI Deps
      run: npm ci
    - name: Fake Install flux
      run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
    - name: Build UI Assets
      run: make cmd/ui/dist/index.html
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        args: --build-tags acceptance

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    - name: Build UI Assets
      run: make cmd/ui/dist/index.html
    - name: build
      run: make
    - name: Store wego binaries
      uses: actions/upload-artifact@v2
      with:
          name: wego-binaries
          path: bin
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    - name: NPM Audit
      run: npm audit
    - name: Build UI Assets
      run: make cmd/ui/dist/main.js
    - name: Fake Install flux
      run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
    - name: unit-tests with coverage
      run: |
        go get -u github.com/ory/go-acc
        go-acc --ignore fluxopsfakes,acceptance -o coverage.out ./... -- -v --timeout=496s -tags test
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  smoke-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Kubernetes
      uses: helm/kind-action@v1.1.0
      with:
        cluster_name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.10.0"
    - name: Kind-check
      run: |
       kubectl get pods -A
    - name: Download wego binaries
      uses: actions/download-artifact@v2
      with:
        name: wego-binaries
        path: bin
    - name: Change bin permissions
      run: |
        chmod +x bin/wego
        ls -la bin
    - name: Download dependecies
      run: |
        make dependencies
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WKP_EXAMPLE_ORG_SSH_KEY }}
    - name: Configure git settings
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "weave-test-user@example.com"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    - name: Install Ginkgo binary
      run: go get github.com/onsi/ginkgo/ginkgo@v1.16.1
    - name: Run smoke tests from acceptance suite
      env:
        GITHUB_ORG: wkp-example-org
        GITHUB_TOKEN: "${{ secrets.WKP_EXAMPLE_ORG_KEY }}"
        GITHUB_KEY: "${{ secrets.WKP_EXAMPLE_ORG_SSH_KEY }}"
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        export WEGO_BIN_PATH=$(pwd)/bin/wego
        go get -u github.com/onsi/ginkgo/ginkgo
        ginkgo --randomizeSuites --reportFile=$(pwd)/test-results/smoke-test-results.xml -v -tags=smoke ./test/acceptance/test/...
