name: Update Components

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: Update component versions
        id: update
        run: |

          source tools/get-flux-update-pr.sh

          {
            echo "::set-output name=pr_body::$PR_BODY"
            echo "::set-output name=pr_title::$PR_TITLE"
          }
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@9825ae65b1cb54b543b938503728b432a0176d29 # v3
        with:
          token: ${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}
          commit-message: |
            ${{ steps.update.outputs.pr_title }}
            ${{ steps.update.outputs.pr_body }}
          committer: GitHub <noreply@github.com>
          author: weave-test-user <weave-test-user@example.com>
          signoff: true
          branch: update-flux2-version
          title: ${{ steps.update.outputs.pr_title }}
          body: |
            ${{ steps.update.outputs.pr_body }}

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"