on:
  push:
    paths-ignore:
      - "doc/**"
    branches:
      - v2
  pull_request:
    branches:
      - v2
  workflow_dispatch:

env:
  CI_CONTAINER_REGISTRY: europe-west1-docker.pkg.dev
  CI_CONTAINER_REPOSITORY: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops

name: V2 CI Workflow
jobs:
  ci-js:
    name: V2 CI Check JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    steps:
      - uses: actions/checkout@v2
      - name: Node modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make dependencies
      - run: make node_modules
      - run: make ui-audit
      - run: make ui
      - run: make ui-lint
      - run: make ui-test
  ci-go:
    name: V2 CI Check Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.5]
    steps:
      - uses: actions/checkout@v2
      - name: Go modules cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up kubebuilder
        uses: fluxcd/pkg/actions/kubebuilder@main
      - run: make dependencies
      - run: go mod download
      - run: make gitops
      - run: make gitops-server
      - run: make unit-tests
      # - run: make lib-test

  ci-static:
    name: V2 CI Check Static Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.5]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: make dependencies
      - run: make check-format
      - run: make lint
      - run: make proto
      - name: Check that proto is updated
        run: git diff --no-ext-diff --exit-code
      - run: make fakes
      - name: Check that fakes are updated
        run: git diff --no-ext-diff --exit-code

  full-ci:
    name: V2 CI Check (16.13.2, 1.17.5)
    runs-on: ubuntu-latest
    needs: [ci-go, ci-static, ci-js]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: gcloud-auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}
      - uses: google-github-actions/setup-gcloud@v0
      - run: gcloud --quiet auth configure-docker ${{ env.CI_CONTAINER_REGISTRY }}
      - run: make dependencies
      - name: Build & push docker iamges to Google
        run: DOCKER_REGISTRY=${{ env.CI_CONTAINER_REPOSITORY }} make docker-image-push

      - run: echo "All done"
